#include "pch.h"
#include "Graphics/Sprite/SpriteRenderComponent.hpp"

#pragma region Reflection
REFL_REGISTER_START(SpriteRenderComponent)
	REFL_REGISTER_PROPERTY(isVisible)
	REFL_REGISTER_PROPERTY(textureGUID)
	REFL_REGISTER_PROPERTY(shaderGUID)
	REFL_REGISTER_PROPERTY(position)
	REFL_REGISTER_PROPERTY(scale)
	REFL_REGISTER_PROPERTY(rotation)
	REFL_REGISTER_PROPERTY(color)
	REFL_REGISTER_PROPERTY(alpha)
	REFL_REGISTER_PROPERTY(is3D)
	REFL_REGISTER_PROPERTY(enableBillboard)
	REFL_REGISTER_PROPERTY(sortingLayer)
	REFL_REGISTER_PROPERTY(sortingOrder)
	REFL_REGISTER_PROPERTY(saved3DPosition)
REFL_REGISTER_END
#pragma endregion