#include "pch.h"
#include "Video/VideoComponent.hpp"

#pragma region Reflection

REFL_REGISTER_START(CutsceneBoard)
	REFL_REGISTER_PROPERTY(imagePath)
	REFL_REGISTER_PROPERTY(text)
	REFL_REGISTER_PROPERTY(textSpeed)
	REFL_REGISTER_PROPERTY(continueText)
	REFL_REGISTER_PROPERTY(duration)
	REFL_REGISTER_PROPERTY(fadeDuration)
	REFL_REGISTER_PROPERTY(blurDelay)
	REFL_REGISTER_PROPERTY(blurIntensity)
	REFL_REGISTER_PROPERTY(blurIntensityEnd)
	REFL_REGISTER_PROPERTY(blurRadius)
	REFL_REGISTER_PROPERTY(blurPasses)
	REFL_REGISTER_PROPERTY(disableFadeOut)
	REFL_REGISTER_PROPERTY(sfxGuidStr)
REFL_REGISTER_END

REFL_REGISTER_START(VideoComponent)
	REFL_REGISTER_PROPERTY(enabled)
	REFL_REGISTER_PROPERTY(cutsceneName)
	REFL_REGISTER_PROPERTY(textEntityGuidStr)
	REFL_REGISTER_PROPERTY(blackScreenEntityGuidStr)
	REFL_REGISTER_PROPERTY(skipButtonEntityGuidStr)
	REFL_REGISTER_PROPERTY(skipFadeDuration)
	REFL_REGISTER_PROPERTY(autoStart)
	REFL_REGISTER_PROPERTY(loop)
	REFL_REGISTER_PROPERTY(nextScenePath)
	REFL_REGISTER_PROPERTY(boards)
	REFL_REGISTER_PROPERTY(cutsceneEnded)
	REFL_REGISTER_PROPERTY(skipRequested)
	REFL_REGISTER_PROPERTY(startDelay)
REFL_REGISTER_END

#pragma endregion
