#include "pch.h"
#include "Graphics/Particle/ParticleComponent.hpp"

#pragma region Reflection
REFL_REGISTER_START(ParticleComponent)
REFL_REGISTER_PROPERTY(isVisible)
REFL_REGISTER_PROPERTY(textureGUID)
REFL_REGISTER_PROPERTY(emitterPosition)
REFL_REGISTER_PROPERTY(emissionRate)
REFL_REGISTER_PROPERTY(maxParticles)
REFL_REGISTER_PROPERTY(particleLifetime)
REFL_REGISTER_PROPERTY(startSize)
REFL_REGISTER_PROPERTY(endSize)
REFL_REGISTER_PROPERTY(startColor)
REFL_REGISTER_PROPERTY(startColorAlpha)
REFL_REGISTER_PROPERTY(endColor)
REFL_REGISTER_PROPERTY(endColorAlpha)
REFL_REGISTER_PROPERTY(gravity)
REFL_REGISTER_PROPERTY(velocityRandomness)
REFL_REGISTER_PROPERTY(initialVelocity)
REFL_REGISTER_END
#pragma endregion