#include "pch.h"
#include "Graphics/Lights/LightComponent.hpp"

#pragma region Reflection
REFL_REGISTER_START(LightComponent)
	REFL_REGISTER_PROPERTY(color)
	REFL_REGISTER_PROPERTY(intensity)
	REFL_REGISTER_PROPERTY(enabled)
REFL_REGISTER_END

REFL_REGISTER_START(DirectionalLightComponent)
	REFL_REGISTER_PROPERTY(direction)
	REFL_REGISTER_PROPERTY(ambient)
	REFL_REGISTER_PROPERTY(diffuse)
	REFL_REGISTER_PROPERTY(specular)
REFL_REGISTER_END

REFL_REGISTER_START(PointLightComponent)
	REFL_REGISTER_PROPERTY(constant)
	REFL_REGISTER_PROPERTY(linear)
	REFL_REGISTER_PROPERTY(quadratic)
	REFL_REGISTER_PROPERTY(ambient)
	REFL_REGISTER_PROPERTY(diffuse)
	REFL_REGISTER_PROPERTY(specular)
REFL_REGISTER_END

REFL_REGISTER_START(SpotLightComponent)
	REFL_REGISTER_PROPERTY(direction)
	REFL_REGISTER_PROPERTY(cutOff)
	REFL_REGISTER_PROPERTY(constant)
	REFL_REGISTER_PROPERTY(linear)
	REFL_REGISTER_PROPERTY(quadratic)
	REFL_REGISTER_PROPERTY(ambient)
	REFL_REGISTER_PROPERTY(diffuse)
	REFL_REGISTER_PROPERTY(specular)
REFL_REGISTER_END
#pragma endregion